version: '3.8'

services:

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: npm run dev -- --host
    volumes:
      - ./frontend/:/your-business-frontend
    ports:
      - 80:5173
